const API='/api';let page=1,pages=1,query='',promptHandler=null;const token=localStorage.getItem('nexus_token');
async function call(path,options={}){const headers=Object.assign({'Content-Type':'application/json'},options.headers||{});if(token)headers.Authorization=`Bearer ${token}`;const r=await fetch(API+path,{...options,headers});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.message||`Request failed (${r.status})`);return d}
function esc(v){const d=document.createElement('div');d.textContent=v==null?'':String(v);return d.innerHTML}function showError(m){const e=document.getElementById('errorBox');e.textContent=m;e.style.display='block'}function clearError(){document.getElementById('errorBox').style.display='none'}
function modal(title,html,onConfirm,confirmText='Confirm',danger=false){document.getElementById('promptTitle').textContent=title;document.getElementById('promptContent').innerHTML=html;promptHandler=onConfirm;const b=document.getElementById('promptConfirm');b.textContent=confirmText;b.className='btn '+(danger?'danger':'primary');document.getElementById('promptModal').classList.add('active')}function closePrompt(){document.getElementById('promptModal').classList.remove('active');promptHandler=null}
async function boot(){try{const me=await call('/admin/me');document.getElementById('adminGate').style.display='none';document.getElementById('adminApp').style.display='grid';document.getElementById('ownerEmail').textContent=me.user.email;await Promise.all([loadStats(),loadUsers()])}catch(e){document.getElementById('adminIdentity').textContent='Access denied. This page is available only to the email listed in ADMIN_EMAILS.'}}
async function loadStats(){const s=await call('/admin/stats');for(const [id,v] of [['statUsers',s.users],['statActive',s.active],['statPremium',s.premium],['statCommunities',s.communities]])document.getElementById(id).textContent=Number(v||0).toLocaleString()}
async function loadUsers(){clearError();try{const d=await call(`/admin/users?page=${page}&limit=30&q=${encodeURIComponent(query)}`);pages=d.pages;document.getElementById('resultMeta').textContent=`${d.total.toLocaleString()} accounts`;document.getElementById('pageMeta').textContent=`Page ${d.page} of ${d.pages}`;document.getElementById('prevBtn').disabled=d.page<=1;document.getElementById('nextBtn').disabled=d.page>=d.pages;render(d.users)}catch(e){showError(e.message)}}
function render(users){const body=document.getElementById('usersBody');body.innerHTML='';for(const u of users){const tr=document.createElement('tr');tr.innerHTML=`<td><strong>${esc(u.displayName)}</strong><small>@${esc(u.username)} · ${esc(u.role)}</small></td><td>${esc(u.email)}<small>${u.emailVerified?'verified':'unverified'}</small></td><td><span class="pill ${esc(u.accountStatus)}">${esc(u.accountStatus)}</span></td><td>${u.premium.active?'Premium':'Free'}</td><td>${Number(u.nexusCoins||0).toLocaleString()}</td><td>${new Date(u.createdAt).toLocaleDateString()}</td><td><div class="actions"><button class="btn" data-act="details">Details</button><button class="btn" data-act="warn">Warn</button><button class="btn" data-act="status">Status</button><button class="btn" data-act="premium">Premium</button><button class="btn" data-act="coins">Coins</button><button class="btn" data-act="role">Role</button><button class="btn danger" data-act="delete">Delete</button></div></td>`;tr.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>action(u,b.dataset.act));body.appendChild(tr)}}
async function action(u,type){if(type==='details'){try{const d=await call(`/admin/users/${u.id}/details`),s=d.stats,w=(d.user.warnings||[]).map(x=>`<li>${esc(x.message)} <small>${new Date(x.createdAt).toLocaleString()}</small></li>`).join('')||'<li>No warnings</li>';modal(`@${u.username}`,`<div class="detail-grid"><div><span>Email</span><strong>${esc(d.user.email)}</strong></div><div><span>Status</span><strong>${esc(d.user.accountStatus)}</strong></div><div><span>Messages</span><strong>${s.messages}</strong></div><div><span>Conversations</span><strong>${s.conversations}</strong></div><div><span>Calls</span><strong>${s.calls}</strong></div><div><span>Communities</span><strong>${s.communities}</strong></div><div><span>Friend links</span><strong>${s.friendLinks}</strong></div><div><span>Reward claims</span><strong>${s.rewards}</strong></div></div><h4>Warnings</h4><ul>${w}</ul>`,closePrompt,'Close');}catch(e){showError(e.message)}return}
if(type==='warn')modal(`Warn @${u.username}`,`<textarea id="pText" rows="4" maxlength="500" placeholder="Policy violation"></textarea>`,async()=>{await call(`/admin/users/${u.id}/warnings`,{method:'POST',body:JSON.stringify({message:document.getElementById('pText').value})});closePrompt();loadUsers()});
if(type==='status')modal(`Account status · @${u.username}`,`<select id="pStatus"><option>active</option><option>restricted</option><option>suspended</option><option>banned</option></select><textarea id="pReason" rows="3" maxlength="500" placeholder="Reason"></textarea>`,async()=>{await call(`/admin/users/${u.id}/status`,{method:'PATCH',body:JSON.stringify({status:document.getElementById('pStatus').value,reason:document.getElementById('pReason').value})});closePrompt();loadUsers()});
if(type==='premium')modal(`Premium · @${u.username}`,`<select id="pActive"><option value="true">Enable Premium</option><option value="false">Disable Premium</option></select><input id="pUntil" type="date">`,async()=>{const until=document.getElementById('pUntil').value;await call(`/admin/users/${u.id}/premium`,{method:'PATCH',body:JSON.stringify({active:document.getElementById('pActive').value==='true',until:until?new Date(until+'T23:59:59Z').toISOString():null,source:'owner-admin'})});closePrompt();loadUsers()});
if(type==='coins')modal(`Nexus Coins · @${u.username}`,`<input id="pCoins" type="number" min="-1000000" max="1000000" value="100"><small>Positive adds coins; negative removes them.</small>`,async()=>{await call(`/admin/users/${u.id}/coins`,{method:'PATCH',body:JSON.stringify({amount:Number(document.getElementById('pCoins').value)})});closePrompt();loadUsers()});
if(type==='role')modal(`Staff role · @${u.username}`,`<select id="pRole"><option>user</option><option>moderator</option><option>admin</option></select><small>Staff roles do not grant Owner Control Center access. Only ADMIN_EMAILS does.</small>`,async()=>{await call(`/admin/users/${u.id}/role`,{method:'PATCH',body:JSON.stringify({role:document.getElementById('pRole').value})});closePrompt();loadUsers()});
if(type==='delete')modal(`Permanently delete @${u.username}`,`<div class="danger-note">This permanently deletes the account and related direct conversations, messages, calls, rewards, and communities owned by this account.</div><label>Type username</label><input id="pConfirmUser" placeholder="${esc(u.username)}"><label>Your admin password</label><input id="pAdminPassword" type="password" placeholder="Owner password">`,async()=>{await call(`/admin/users/${u.id}`,{method:'DELETE',body:JSON.stringify({confirmUsername:document.getElementById('pConfirmUser').value,adminPassword:document.getElementById('pAdminPassword').value})});closePrompt();await Promise.all([loadStats(),loadUsers()])},'Delete permanently',true)}

document.getElementById('searchBtn').onclick=()=>{query=document.getElementById('searchBox').value.trim();page=1;loadUsers()};document.getElementById('searchBox').onkeydown=e=>{if(e.key==='Enter')document.getElementById('searchBtn').click()};document.getElementById('prevBtn').onclick=()=>{if(page>1){page--;loadUsers()}};document.getElementById('nextBtn').onclick=()=>{if(page<pages){page++;loadUsers()}};document.getElementById('refreshBtn').onclick=()=>Promise.all([loadStats(),loadUsers()]);document.getElementById('promptCancel').onclick=closePrompt;document.getElementById('promptX').onclick=closePrompt;document.getElementById('promptConfirm').onclick=async()=>{if(promptHandler){try{clearError();await promptHandler()}catch(e){showError(e.message)}}};boot();
