
/* NexusChat Professional UX helpers — home, community management, rewards navigation. */
let nexusHomeTab='online';
function wireProfessionalUX(){
  document.querySelectorAll('.home-tab').forEach(b=>b.addEventListener('click',()=>switchHomeTab(b.dataset.homeTab)));
  document.getElementById('homeFriendSearch')?.addEventListener('input',renderProfessionalHome);
  document.getElementById('homeAddFriendBtn')?.addEventListener('click',async()=>{
    const input=document.getElementById('homeAddFriendInput'),out=document.getElementById('homeAddFriendState');
    const username=input.value.trim().toLowerCase(); if(!username){out.textContent='Enter a username.';return;}
    try{await apiFetch('/friends/request',{method:'POST',body:JSON.stringify({username})});out.textContent='Friend request sent.';input.value='';await loadFriendRequests();renderProfessionalHome();}catch(e){out.textContent=e.message;}
  });
  document.getElementById('homeRewardsShortcut')?.addEventListener('click',openRewardsModal);
  document.getElementById('communityManageBtn')?.addEventListener('click',openCommunitySettingsPro);
  document.querySelectorAll('.cs-tab[data-cs-tab]').forEach(b=>b.addEventListener('click',()=>switchCommunitySettingsTab(b.dataset.csTab)));
  document.getElementById('csSaveOverview')?.addEventListener('click',saveCommunityOverview);
  document.getElementById('csAddCategory')?.addEventListener('click',addCommunityCategory);
  document.getElementById('csRotateInvite')?.addEventListener('click',rotateInvitePro);
  document.getElementById('csCopyInvite')?.addEventListener('click',()=>copyText(state.activeCommunity?.inviteCode||''));
  document.getElementById('csLeaveBtn')?.addEventListener('click',async()=>{closeModal('communitySettingsModal');await leaveCommunity();});
  document.getElementById('csDeleteBtn')?.addEventListener('click',async()=>{closeModal('communitySettingsModal');await deleteCommunity();});
}
function showHomeView(){
  const home=document.getElementById('homeView'),empty=document.getElementById('emptyState'),chat=document.getElementById('chatView'),community=document.getElementById('communityView');
  if(home)home.classList.add('active'); if(empty)empty.style.display='none';chat?.classList.remove('active');community?.classList.remove('active');renderProfessionalHome();
}
function hideHomeView(){document.getElementById('homeView')?.classList.remove('active');}
function switchHomeTab(tab){nexusHomeTab=tab;document.querySelectorAll('.home-tab').forEach(b=>b.classList.toggle('active',b.dataset.homeTab===tab));renderProfessionalHome();}
function renderProfessionalHome(){
  const list=document.getElementById('homeFriendsList');if(!list)return;
  const pending=document.getElementById('homePendingPanel'),add=document.getElementById('homeAddPanel');list.style.display='';pending.style.display='none';add.style.display='none';
  const badge=document.getElementById('homePendingBadge'),pc=state.requests?.incoming?.length||0;if(badge){badge.textContent=pc;badge.style.display=pc?'inline':'none';}
  if(nexusHomeTab==='pending'){list.style.display='none';pending.style.display='block';renderHomePending();return;}
  if(nexusHomeTab==='add'){list.style.display='none';add.style.display='block';return;}
  const q=(document.getElementById('homeFriendSearch')?.value||'').toLowerCase();
  let rows=(state.friends||[]).filter(f=>!q||f.username.toLowerCase().includes(q)||(f.displayName||'').toLowerCase().includes(q));
  if(nexusHomeTab==='online')rows=rows.filter(f=>(state.presence[f.username]||{}).online);
  document.getElementById('homeFriendSummary').textContent=`${nexusHomeTab==='online'?'ONLINE':'ALL FRIENDS'} — ${rows.length}`;
  list.innerHTML='';
  if(!rows.length){list.innerHTML='<div class="dm-empty">No friends to show here yet.</div>';} else rows.forEach(f=>list.appendChild(buildHomeFriendRow(f)));
  renderActiveNow();
}
function buildHomeFriendRow(f){
  const p=state.presence[f.username]||{};const row=document.createElement('div');row.className='home-friend-row';row.innerHTML=`<div class="home-friend-avatar"><div class="home-avatar-fill"></div><span class="status-dot ${p.online?'online':'offline'}"></span></div><div class="home-friend-copy"><strong>${escapeHtml(f.displayName||f.username)}</strong><small>${p.online?(f.status?escapeHtml(f.status):'Online'):'Offline'} · @${escapeHtml(f.username)}</small></div><div class="home-friend-actions"><button class="home-action-btn" title="Message">●</button><button class="home-action-btn" title="Profile">⋯</button></div>`;
  applyPfpToEl(row.querySelector('.home-avatar-fill'),f.avatar,f.displayName||f.username);row.querySelectorAll('button')[0].addEventListener('click',()=>openChat(f.username));row.querySelectorAll('button')[1].addEventListener('click',()=>openProfilePopout(f.username,false));row.addEventListener('dblclick',()=>openChat(f.username));return row;
}
function renderActiveNow(){const host=document.getElementById('activeNowList'),empty=document.getElementById('activeNowEmpty');if(!host)return;host.innerHTML='';const online=(state.friends||[]).filter(f=>(state.presence[f.username]||{}).online).slice(0,8);empty.style.display=online.length?'none':'flex';online.forEach(f=>{const d=document.createElement('button');d.className='active-now-user';d.innerHTML='<div class="home-friend-avatar"><div class="home-avatar-fill"></div></div><div><strong>'+escapeHtml(f.displayName||f.username)+'</strong><small>Online</small></div>';applyPfpToEl(d.querySelector('.home-avatar-fill'),f.avatar,f.displayName||f.username);d.addEventListener('click',()=>openChat(f.username));host.appendChild(d);});}
function renderHomePending(){const h=document.getElementById('homePendingPanel');h.innerHTML='<div class="friends-summary">PENDING — '+((state.requests?.incoming?.length||0)+(state.requests?.outgoing?.length||0))+'</div>';const all=[...(state.requests?.incoming||[]).map(x=>({...x,_incoming:true})),...(state.requests?.outgoing||[]).map(x=>({...x,_incoming:false}))];if(!all.length){h.innerHTML+='<div class="dm-empty">No pending friend requests.</div>';return;}all.forEach(r=>{const row=document.createElement('div');row.className='home-friend-row';row.innerHTML='<div class="home-friend-avatar"><div class="home-avatar-fill"></div></div><div class="home-friend-copy"><strong>'+escapeHtml(r.displayName||r.username)+'</strong><small>@'+escapeHtml(r.username)+' · '+(r._incoming?'Incoming request':'Outgoing request')+'</small></div><div class="home-friend-actions"></div>';applyPfpToEl(row.querySelector('.home-avatar-fill'),r.avatar,r.displayName||r.username);const a=row.querySelector('.home-friend-actions');if(r._incoming){const ok=document.createElement('button');ok.className='btn-primary small';ok.textContent='Accept';ok.onclick=async()=>{await respondToRequest(r.id,true);renderProfessionalHome()};a.appendChild(ok);}const no=document.createElement('button');no.className='btn-ghost small';no.textContent=r._incoming?'Ignore':'Cancel';no.onclick=async()=>{r._incoming?await respondToRequest(r.id,false):await cancelRequest(r.id);renderProfessionalHome()};a.appendChild(no);h.appendChild(row);});}
function copyText(text){if(!text)return;navigator.clipboard?.writeText(text).then(()=>showToast?.('Copied to clipboard.')).catch(()=>{});}

function openCommunitySettingsPro(){const c=state.activeCommunity;if(!c)return;if(!['owner','admin'].includes(c.role)){showToast?.('Only community admins can open community settings.');return;}document.getElementById('csNavName').textContent=c.name;document.getElementById('csName').value=c.name||'';document.getElementById('csDescription').value=c.description||'';document.getElementById('csIcon').value=c.icon||'';document.getElementById('csInviteCode').textContent=c.inviteCode||'—';document.getElementById('csDeleteBtn').style.display=c.role==='owner'?'block':'none';switchCommunitySettingsTab('overview');renderCommunitySettingsData();openModal('communitySettingsModal');}
function switchCommunitySettingsTab(tab){document.querySelectorAll('.cs-tab[data-cs-tab]').forEach(b=>b.classList.toggle('active',b.dataset.csTab===tab));document.querySelectorAll('.cs-page').forEach(p=>p.classList.toggle('active',p.dataset.csPage===tab));if(tab==='members')renderCsMembers();if(tab==='channels')renderCsCategories();if(tab==='moderation')renderCsBans();}
async function renderCommunitySettingsData(){if(!state.activeCommunity)return;try{const d=await apiFetch(`/communities/${state.activeCommunity.id}`);state.activeCommunity=d.community;document.getElementById('csInviteCode').textContent=d.community.inviteCode||'—';renderCsCategories();renderCsMembers();renderCsBans();}catch(e){showToast?.(e.message);}}
async function saveCommunityOverview(){const c=state.activeCommunity;if(!c)return;try{const d=await apiFetch(`/communities/${c.id}`,{method:'PATCH',body:JSON.stringify({name:document.getElementById('csName').value.trim(),description:document.getElementById('csDescription').value.trim(),icon:document.getElementById('csIcon').value.trim()})});state.activeCommunity=d.community;await loadCommunities();document.getElementById('communitySidebarName').textContent=d.community.name;document.getElementById('communitySidebarDescription').textContent=d.community.description||`${d.community.memberCount} members`;document.getElementById('csNavName').textContent=d.community.name;showToast?.('Community updated.');}catch(e){showToast?.(e.message);}}
function communityCategories(){const c=state.activeCommunity;if(!c)return[];if(c.categories?.length)return [...c.categories].sort((a,b)=>a.position-b.position);const seen=[];(c.channels||[]).forEach(ch=>{if(!seen.includes(ch.category))seen.push(ch.category)});return seen.map((name,i)=>({id:name,name,position:i}));}
function renderCsCategories(){const h=document.getElementById('csCategoriesList');if(!h||!state.activeCommunity)return;h.innerHTML='';communityCategories().forEach(cat=>{const channels=(state.activeCommunity.channels||[]).filter(ch=>ch.category===cat.name);const row=document.createElement('div');row.className='cs-row';row.innerHTML=`<div class="cs-row-copy"><strong>${escapeHtml(cat.name)}</strong><small>${channels.length} channel${channels.length===1?'':'s'}</small></div><div class="cs-row-actions"><button class="btn-ghost small">Rename</button><button class="btn-ghost small">+ Channel</button><button class="btn-danger small">Delete</button></div>`;const [ren,add,del]=row.querySelectorAll('button');ren.onclick=()=>renameCommunityCategory(cat);add.onclick=()=>openCreateChannelForCategory(cat.name);del.onclick=()=>deleteCommunityCategory(cat);h.appendChild(row);channels.forEach(ch=>{const cr=document.createElement('div');cr.className='cs-row channel-child';cr.innerHTML=`<div class="cs-row-copy"><strong>${ch.type==='voice'?'◖':'#'} ${escapeHtml(ch.name)}</strong><small>${ch.type} channel</small></div><div class="cs-row-actions"><button class="btn-ghost small">Rename</button><button class="btn-danger small">Delete</button></div>`;const [r,d]=cr.querySelectorAll('button');r.onclick=()=>manageCommunityChannelRenamePro(ch);d.onclick=()=>deleteCommunityChannelPro(ch);h.appendChild(cr);});});}
async function addCommunityCategory(){const name=prompt('Category name');if(!name?.trim()||!state.activeCommunity)return;try{const d=await apiFetch(`/communities/${state.activeCommunity.id}/categories`,{method:'POST',body:JSON.stringify({name:name.trim()})});state.activeCommunity=d.community;renderCommunityChannels();renderCsCategories();}catch(e){showToast?.(e.message);}}
async function renameCommunityCategory(cat){const name=prompt('Rename category',cat.name);if(!name?.trim()||!state.activeCommunity)return;try{const d=await apiFetch(`/communities/${state.activeCommunity.id}/categories/${encodeURIComponent(cat.id)}`,{method:'PATCH',body:JSON.stringify({name:name.trim()})});state.activeCommunity=d.community;renderCommunityChannels();renderCsCategories();}catch(e){showToast?.(e.message);}}
async function deleteCommunityCategory(cat){if(!confirm(`Delete category “${cat.name}”? Channels will move to General.`)||!state.activeCommunity)return;try{const d=await apiFetch(`/communities/${state.activeCommunity.id}/categories/${encodeURIComponent(cat.id)}`,{method:'DELETE'});state.activeCommunity=d.community;renderCommunityChannels();renderCsCategories();}catch(e){showToast?.(e.message);}}
function openCreateChannelForCategory(category){document.getElementById('channelNameInput').value='';document.getElementById('channelCreateForm').dataset.category=category;openModal('channelCreateModal');}
async function manageCommunityChannelRenamePro(ch){const name=prompt('New channel name',ch.name);if(!name?.trim())return;try{const d=await apiFetch(`/communities/${state.activeCommunity.id}/channels/${ch.id}`,{method:'PATCH',body:JSON.stringify({name:name.trim()})});state.activeCommunity=d.community;renderCommunityChannels();renderCsCategories();}catch(e){showToast?.(e.message);}}
async function deleteCommunityChannelPro(ch){if(!confirm(`Delete #${ch.name}?`))return;try{const d=await apiFetch(`/communities/${state.activeCommunity.id}/channels/${ch.id}`,{method:'DELETE'});state.activeCommunity=d.community;renderCommunityChannels();renderCsCategories();}catch(e){showToast?.(e.message);}}
function renderCsMembers(){const h=document.getElementById('csMembersList');if(!h||!state.activeCommunity)return;h.innerHTML='';(state.activeCommunity.members||[]).forEach(m=>{const u=m.user||{};const row=document.createElement('div');row.className='cs-row';row.innerHTML='<div class="community-member-avatar"></div><div class="cs-row-copy"><strong>'+escapeHtml(u.displayName||u.username||'Member')+'</strong><small>@'+escapeHtml(u.username||'')+' · '+escapeHtml(m.role||'member')+'</small></div><div class="cs-row-actions"></div>';applyPfpToEl(row.querySelector('.community-member-avatar'),u.avatar,u.displayName||u.username);const a=row.querySelector('.cs-row-actions');if(m.role!=='owner'){if(state.activeCommunity.role==='owner'){const role=document.createElement('button');role.className='btn-ghost small';role.textContent=m.role==='admin'?'Make Member':'Make Admin';role.onclick=()=>changeCsRole(u.id||u._id,m.role==='admin'?'member':'admin');a.appendChild(role);}const kick=document.createElement('button');kick.className='btn-ghost small';kick.textContent='Kick';kick.onclick=()=>kickCsMember(u.id||u._id,u.username);a.appendChild(kick);const ban=document.createElement('button');ban.className='btn-danger small';ban.textContent='Ban';ban.onclick=()=>banCsMember(u.id||u._id,u.username);a.appendChild(ban);}h.appendChild(row);});}
async function changeCsRole(id,role){try{const d=await apiFetch(`/communities/${state.activeCommunity.id}/members/${id}/role`,{method:'PATCH',body:JSON.stringify({role})});await renderCommunitySettingsData();showToast?.('Role updated.');}catch(e){showToast?.(e.message);}}
async function kickCsMember(id,name){if(!confirm(`Remove @${name} from this community?`))return;try{await apiFetch(`/communities/${state.activeCommunity.id}/members/${id}`,{method:'DELETE'});await renderCommunitySettingsData();showToast?.('Member removed.');}catch(e){showToast?.(e.message);}}
async function banCsMember(id,name){if(!confirm(`Ban @${name}? They will not be able to rejoin using an invite.`))return;try{await apiFetch(`/communities/${state.activeCommunity.id}/members/${id}/ban`,{method:'POST'});await renderCommunitySettingsData();showToast?.('Member banned.');}catch(e){showToast?.(e.message);}}
function renderCsBans(){const h=document.getElementById('csBannedList');if(!h)return;const bans=state.activeCommunity?.bannedUsers||[];h.innerHTML=bans.length?'':'<div class="dm-empty">No banned members.</div>';bans.forEach(u=>{const row=document.createElement('div');row.className='cs-row';row.innerHTML='<div class="cs-row-copy"><strong>'+escapeHtml(u.displayName||u.username||'User')+'</strong><small>@'+escapeHtml(u.username||'')+'</small></div><button class="btn-ghost small">Unban</button>';row.querySelector('button').onclick=async()=>{try{await apiFetch(`/communities/${state.activeCommunity.id}/bans/${u.id||u._id}`,{method:'DELETE'});await renderCommunitySettingsData();}catch(e){showToast?.(e.message)}};h.appendChild(row);});}
async function rotateInvitePro(){const expiry=document.getElementById('csInviteExpiry').value,max=document.getElementById('csInviteMaxUses').value;const body={};if(expiry)body.expiresInHours=Number(expiry);if(max)body.maxUses=Number(max);try{const d=await apiFetch(`/communities/${state.activeCommunity.id}/invite/rotate`,{method:'POST',body:JSON.stringify(body)});state.activeCommunity.inviteCode=d.inviteCode;state.activeCommunity.inviteExpiresAt=d.inviteExpiresAt;state.activeCommunity.inviteMaxUses=d.inviteMaxUses;document.getElementById('csInviteCode').textContent=d.inviteCode;document.getElementById('csInviteMeta').textContent='New invite generated.';showToast?.('Invite generated.');}catch(e){showToast?.(e.message);}}
